# Autogenerated wrapper script for libfyaml_jll for armv7l-linux-gnueabihf
export fy_compose, fy_dump, fy_filter, fy_join, fy_testsuite, fy_tool, fy_ypath, libfyaml_c

JLLWrappers.@generate_wrapper_header("libfyaml")
JLLWrappers.@declare_library_product(libfyaml_c, "libfyaml.so.0")
JLLWrappers.@declare_executable_product(fy_compose)
JLLWrappers.@declare_executable_product(fy_dump)
JLLWrappers.@declare_executable_product(fy_filter)
JLLWrappers.@declare_executable_product(fy_join)
JLLWrappers.@declare_executable_product(fy_testsuite)
JLLWrappers.@declare_executable_product(fy_tool)
JLLWrappers.@declare_executable_product(fy_ypath)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfyaml_c,
        "lib/libfyaml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        fy_compose,
        "bin/fy-compose",
    )

    JLLWrappers.@init_executable_product(
        fy_dump,
        "bin/fy-dump",
    )

    JLLWrappers.@init_executable_product(
        fy_filter,
        "bin/fy-filter",
    )

    JLLWrappers.@init_executable_product(
        fy_join,
        "bin/fy-join",
    )

    JLLWrappers.@init_executable_product(
        fy_testsuite,
        "bin/fy-testsuite",
    )

    JLLWrappers.@init_executable_product(
        fy_tool,
        "bin/fy-tool",
    )

    JLLWrappers.@init_executable_product(
        fy_ypath,
        "bin/fy-ypath",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
